# Site settings
title: Web Developer
email: johncarverhoward@gmail.com
url: https://jackhowa.github.io
description: "I want to make your site more accessible."
skills: "Full-Stack Developer - Product Management - Data Visualization"
meta_author: Howard Jack

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: jackhowa

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6C7A89 #lynch http://www.flatuicolorpicker.com/category/new
  primary-rgb: "108, 122, 137"
  secondary: F89406 #FD6E8A F89406
  secondary-dark: F89406 #A2122F

# Footer settings
footer:
  copyright: Jack Howard 
  location: Chicago 
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: "Chicago, IL"
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
